name = "Overthrow 0.6.6"; //This name will be displayed only in game , specifically the expansion menu 
picture = "logo_overthrow.paa"; //Location of your addon's icon
logo = "logo_overthrow.paa";
logoOver = "logo_overthrow.paa";
actionName = "Github";   //The name of the action 
action = "https://github.com/armazac/Overthrow.Tanoa"; //The action , "Authors Website Link"
description = "Overthrow - Version 0.6.6"; // Addon Description
overview = "A Revolution Simulator for Arma 3";
author = "ARMAzac";
overviewPicture = "logo_overthrow.paa";